import type { ClientProject } from "@/types/portfolio";

export const clientProjects: ClientProject[] = [
  {
    name: "GM Aerotech",
    url: "https://gmaerotech.in/",
    category: "aerospace",
    year: "2026",
    summary: "A technical web presence for an aerospace-focused company with a clean industrial tone.",
    services: ["Website", "Brand UI", "Performance"],
    accent: "cyan",
  },
  {
    name: "Vril Innovation",
    url: "https://vrilinnovation.in/",
    category: "innovation",
    year: "2026",
    summary: "A future-facing company site shaped around products, research, and credibility.",
    services: ["Website", "UX Design", "Content System"],
    accent: "violet",
  },
  {
    name: "NDRF",
    url: "https://www.ndrf.res.in/",
    category: "public-sector",
    year: "2026",
    summary: "A public-sector digital platform built for clarity, access, and structured information.",
    services: ["Web Platform", "Information Design", "Responsive UI"],
    accent: "blue",
  },
  {
    name: "MA Quality Products",
    url: "https://www.ma-quality-products.online/",
    category: "commerce",
    year: "2026",
    summary: "A product-led commerce experience focused on trust, discoverability, and conversion.",
    services: ["E-Commerce", "Catalog UI", "Mobile UX"],
    accent: "cyan",
  },
  {
    name: "Ayasya Yoga",
    url: "https://ayasyayoga.in/",
    category: "wellness",
    year: "2026",
    summary: "A calm wellness experience for programs, brand presence, and customer discovery.",
    services: ["Website", "Booking Flow", "Responsive Design"],
    accent: "violet",
  },
  {
    name: "Hotel Ashokavana",
    url: "https://www.hotelashokavana.com/index.html?message=successfully+sent.",
    category: "hospitality",
    year: "2026",
    summary: "A hospitality site designed around destination confidence and direct enquiries.",
    services: ["Website", "Lead Flow", "Local SEO"],
    accent: "blue",
  },
  {
    name: "Qaser Al Talah",
    url: "https://qaseraltalah.com/",
    category: "hospitality",
    year: "2026",
    summary: "A polished hospitality presence with emphasis on premium browsing and trust.",
    services: ["Website", "Visual UI", "Performance"],
    accent: "cyan",
  },
  {
    name: "Vibrant Ritchie",
    url: "https://vibrant-ritchie-2c5d13.netlify.app/",
    category: "web",
    year: "2026",
    summary: "A fast web deployment showcasing a focused digital experience and clean delivery.",
    services: ["Web Build", "Deployment", "Responsive UI"],
    accent: "violet",
  },
  {
    name: "Ceyone Society",
    url: "http://ceyonesociety.org/",
    category: "community",
    year: "2026",
    summary: "A community-oriented web presence structured for communication and accessibility.",
    services: ["Website", "CMS Structure", "Information Design"],
    accent: "blue",
  },
];
