import type { ClientProject } from "@/types/portfolio";

export const clientProjects: ClientProject[] = [
  {
    slug: "gm-aerotech",
    name: "GM Aerotech",
    url: "https://gmaerotech.in/",
    category: "aerospace",
    year: "2022",
    summary: "A technical web presence for an aerospace-focused company with a clean industrial tone.",
    challenge: "Present a specialized aerospace business with enough clarity for serious buyers while keeping the interface fast, modern, and credible.",
    solution: "We shaped a focused company website with industrial visual language, structured service sections, mobile-first information flow, and performance-conscious pages.",
    result: "The brand now has a sharper technical presence that communicates capability quickly and gives prospects a clear path to enquiry.",
    services: ["Website", "Brand UI", "Performance"],
    stack: ["Next.js", "Responsive UI", "SEO", "Performance"],
    metrics: [["focus", "technical trust"], ["surface", "company website"], ["priority", "speed + clarity"]],
    accent: "cyan",
  },
  {
    slug: "vril-innovation",
    name: "Vril Innovation",
    url: "https://vrilinnovation.in/",
    category: "innovation",
    year: "2021",
    summary: "A future-facing company site shaped around products, research, and credibility.",
    challenge: "Create a web identity that feels innovative without becoming vague, decorative, or difficult to scan.",
    solution: "We built a product-forward structure with clean navigation, credibility-focused copy sections, and a visual system that supports research and innovation messaging.",
    result: "The website gives the company a more future-facing digital presence with a stronger first impression and clearer product storytelling.",
    services: ["Website", "UX Design", "Content System"],
    stack: ["React", "Content Structure", "UX Design", "Responsive Layout"],
    metrics: [["focus", "innovation story"], ["surface", "brand site"], ["priority", "credibility"]],
    accent: "violet",
  },
  {
    slug: "ndrf",
    name: "NDRF",
    url: "https://www.ndrf.res.in/",
    category: "public-sector",
    year: "2018",
    summary: "A public-sector digital platform built for clarity, access, and structured information.",
    challenge: "Public-sector users need fast access to information, predictable navigation, and readable content across many device types.",
    solution: "We prioritized information architecture, responsive structure, accessibility-minded layouts, and content grouping that helps visitors find official information faster.",
    result: "The platform is easier to scan, more structured for public communication, and better suited for repeated information access.",
    services: ["Web Platform", "Information Design", "Responsive UI"],
    stack: ["Information Architecture", "Responsive UI", "Accessibility", "Content Design"],
    metrics: [["focus", "public access"], ["surface", "information portal"], ["priority", "clarity"]],
    accent: "blue",
  },
  {
    slug: "ma-quality-products",
    name: "MA Quality Products",
    url: "https://www.ma-quality-products.online/",
    category: "commerce",
    year: "2026",
    summary: "A product-led commerce experience focused on trust, discoverability, and conversion.",
    challenge: "Turn a product catalog into a trustworthy browsing experience that works well on mobile and supports buying intent.",
    solution: "We created a catalog-led interface with product grouping, trust cues, mobile-friendly browsing, and clear enquiry/conversion paths.",
    result: "Visitors can understand the product offering faster and move from browsing to enquiry with less friction.",
    services: ["E-Commerce", "Catalog UI", "Mobile UX"],
    stack: ["Catalog UX", "Mobile UI", "Conversion Flow", "Product Content"],
    metrics: [["focus", "product discovery"], ["surface", "commerce"], ["priority", "conversion"]],
    accent: "cyan",
  },
  {
    slug: "ayasya-yoga",
    name: "Ayasya Yoga",
    url: "https://ayasyayoga.in/",
    category: "wellness",
    year: "2025",
    summary: "A calm wellness experience for programs, brand presence, and customer discovery.",
    challenge: "Design a wellness presence that feels peaceful and premium while still making programs and enquiry actions clear.",
    solution: "We balanced calming visuals with structured program sections, responsive pages, and direct contact paths for interested visitors.",
    result: "The site gives the brand a calmer, more professional presence and improves discovery for wellness offerings.",
    services: ["Website", "Booking Flow", "Responsive Design"],
    stack: ["Responsive Design", "Program Pages", "Lead Flow", "Brand UI"],
    metrics: [["focus", "wellness trust"], ["surface", "program website"], ["priority", "calm UX"]],
    accent: "violet",
  },
  {
    slug: "hotel-ashokavana",
    name: "Hotel Ashokavana",
    url: "https://www.hotelashokavana.com/index.html?message=successfully+sent.",
    category: "hospitality",
    year: "2024",
    summary: "A hospitality site designed around destination confidence and direct enquiries.",
    challenge: "Hospitality visitors need quick confidence: place, experience, rooms, contact, and enquiry should all be easy to reach.",
    solution: "We shaped a destination-first website with direct enquiry flow, local SEO structure, and mobile-friendly hospitality content.",
    result: "The property has a clearer web presence that supports discovery and direct guest enquiries.",
    services: ["Website", "Lead Flow", "Local SEO"],
    stack: ["Hospitality UX", "Local SEO", "Lead Form", "Mobile Layout"],
    metrics: [["focus", "guest enquiries"], ["surface", "hotel website"], ["priority", "local discovery"]],
    accent: "blue",
  },
  {
    slug: "qaser-al-talah",
    name: "Qaser Al Talah",
    url: "https://qaseraltalah.com/",
    category: "hospitality",
    year: "2025",
    summary: "A polished hospitality presence with emphasis on premium browsing and trust.",
    challenge: "Build a hospitality website that feels premium while staying clear, fast, and easy to browse.",
    solution: "We used a refined visual system, mobile-aware layouts, clear sections, and trust-focused content hierarchy.",
    result: "The website supports a more premium first impression and makes the brand easier to evaluate online.",
    services: ["Website", "Visual UI", "Performance"],
    stack: ["Premium UI", "Responsive Layout", "Performance", "Content Flow"],
    metrics: [["focus", "premium trust"], ["surface", "hospitality"], ["priority", "visual quality"]],
    accent: "cyan",
  },
  {
    slug: "vibrant-ritchie",
    name: "Vibrant Ritchie",
    url: "https://vibrant-ritchie-2c5d13.netlify.app/",
    category: "web",
    year: "2024",
    summary: "A fast web deployment showcasing a focused digital experience and clean delivery.",
    challenge: "Deliver a focused web experience quickly without letting speed reduce interface quality.",
    solution: "We built and deployed a lean responsive site with clear sections, simple interaction states, and production hosting.",
    result: "The project demonstrates fast turnaround with a stable deployment and polished responsive baseline.",
    services: ["Web Build", "Deployment", "Responsive UI"],
    stack: ["React", "Netlify", "Responsive UI", "Deployment"],
    metrics: [["focus", "fast launch"], ["surface", "web build"], ["priority", "delivery"]],
    accent: "violet",
  },
  {
    slug: "ceyone-society",
    name: "Ceyone Society",
    url: "http://ceyonesociety.org/",
    category: "community",
    year: "2021",
    summary: "A community-oriented web presence structured for communication and accessibility.",
    challenge: "Community websites must make updates, purpose, and contact information easy for a broad audience.",
    solution: "We organized content around communication needs, accessible reading, mobile browsing, and simple navigation.",
    result: "The site provides a clearer community presence and makes important information easier to reach.",
    services: ["Website", "CMS Structure", "Information Design"],
    stack: ["Content Structure", "Accessible UI", "Responsive Layout", "Community Pages"],
    metrics: [["focus", "community info"], ["surface", "public website"], ["priority", "readability"]],
    accent: "blue",
  },
  {
    slug: "make-my-project",
    name: "Make My Project",
    url: "https://makemyproject.co.in/",
    category: "web",
    year: "2026",
    summary: "A project-focused web platform built around discovery, clarity, and student-friendly enquiry paths.",
    challenge: "Students and visitors need to understand available project help quickly and trust the enquiry path.",
    solution: "We designed a project-discovery experience with clear service grouping, simple lead flow, and mobile-first content hierarchy.",
    result: "The platform is easier to browse, easier to contact, and better aligned with student project discovery.",
    services: ["Website", "Lead Flow", "Responsive UI"],
    stack: ["Lead Flow", "Responsive UI", "SEO", "Content Design"],
    metrics: [["focus", "student leads"], ["surface", "project platform"], ["priority", "enquiry flow"]],
    accent: "cyan",
  },
];

export function getClientProjectBySlug(slug: string) {
  return clientProjects.find((project) => project.slug === slug);
}
